apiVersion: v1
kind: Secret
metadata:
  name: librenms-secrets
  namespace: librenms
  annotations:
    argocd.argoproj.io/sync-wave: "1"
type: Opaque
stringData:
  DB_USER: "librenms"
  DB_PASSWORD: "Pa$$w0rd"
  APP_KEY: "base64:Cble3ISJRmfVerx2ZqHJrelecVrJ5XKj021qfsK+938="
  SNMP_COMMUNITY: "librenmsdocker"
