apiVersion: apps/v1
kind: Deployment
metadata:
  name: librenms
  namespace: librenms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: librenms
  template:
    metadata:
      labels:
        app: librenms
    spec:
      containers:
      - name: librenms
        image: librenms/librenms:latest
        env:
        - name: DB_HOST
          value: "192.168.44.131"
        - name: DB_DATABASE
          value: "librenms"
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: librenms-secret
              key: db-username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: librenms-secret
              key: db-password
        - name: REDIS_HOST
          value: "redis"
        - name: RRDCACHED_SERVER
          value: "192.168.44.200:42217"
        ports:
        - containerPort: 8000
