apiVersion: v1
kind: Secret
metadata:
    name: librenms-poller-secret
    namespace: librenms
type: Opaque
stringData:
    DB_HOST: ENC[AES256_GCM,data:hpdbS0cQm+ieL+jkl9BNsvzWXdyVai/Knn2e/IlaoOiqrw==,iv:FL8SmAYWCTyLi/wUHuApzRRL3YQ4qtJsh/nEM5ulirE=,tag:Z3yJNvA9ctpnmH9MdhYcqQ==,type:str]
    DB_NAME: ENC[AES256_GCM,data:c5d4VK0Ajs0=,iv:n4OvR9mQoNaJKeIOIGXCwxJX3xzo5zDnViF1wFIQgt8=,tag:tRD0CHcDdfco9R2kVd1oKA==,type:str]
    DB_USER: ENC[AES256_GCM,data:VU5RfVdo/vA=,iv:uzXSospvoL5AlFijFL8U4aIlEQYAct06Xin3Y5jD7Kk=,tag:prq5gDrgIbFYsHYgL/sysw==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:o4lwpbqPqb0=,iv:u7dqzQdwOsqEVumXGtDUIJilKaslytwzUMwRv4mgxGE=,tag:nEj6Hp2+REZ5VEQZMh5kdA==,type:str]
    REDIS_HOST: ENC[AES256_GCM,data:nK3BjSC7vF7xrWg78yW+R7kYFaLVCqwaFrozYIlIgQM=,iv:PHPKQuTHEtwLrxKy0pxXOCQO7G4AZLh3uUae0QJXWrQ=,tag:uKs8C2zjVYCJpmfEX7nbXw==,type:str]
    REDIS_PORT: ENC[AES256_GCM,data:EGVzww==,iv:oKyYaIBZGjomu7gFjEMipKvc2BYjthxROmoc3k7LUNI=,tag:pIZY1lKvcibnqqW8xbMf+g==,type:str]
    APP_KEY: ENC[AES256_GCM,data:hwodXZAVTFKEn6EW5wAhbkolVcKvOagFP+nRMFPp5nJnwTrvC+Zv50A0EOZW4P8R5TOt,iv:7qeR5GggqgplXJWz78rMp6q5u0jim8QMg8Y3H/MAxmI=,tag:wSP1QihTxJ/3bmsLc4a+5g==,type:str]
sops:
    age:
        - recipient: age10953cacvc7svzqscc3rrpxsv7smmkhxj9w3yhcj47dy3a4hgna5shwa46c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrZ1M0amhwQTBHUkRSMnh1
            UzBTZWVYVG1PNWJReTVUOTc4dmNKdkczS25BCjJ1VGwveTNnZFI4dXhPWUVGck9H
            N3VwRXU1QTRQSi9UT0FDZHljU0RabDgKLS0tIDFBakNHVStQcGpMOHIzLzh3Vkt2
            S3VwSmxYRktCNHhmRVUxTEZMVGtobmMKQehaGIA1NYZfCwsUqaVg6h3Um8P6jFBN
            pDxsEt60HiDg9z7bi70+HySauf0YO6FSafC/BUcWMx79tacHxMYQFA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-16T07:26:38Z"
    mac: ENC[AES256_GCM,data:KhzPAmPdLkr0lKpRneNvqc8TZSd0TIFZXZp9oJ84lGF02sP5HwmqMdIfvGz3GA2E8538y84FkrspBV0vmxWcGJU2N1n8yeBJw2hVnFm4FTASlnC3nkhc1g8xxGg9MvyS+47O7rMCoDWE8EC2e3TagYEbgxEYe1akkr8gZEjuBuA=,iv:IjQBqWfOIUv40eEy78Jh0ykgWnLjtQ+EPbRfAQX/ID4=,tag:bER2OxjOjE06dXvzS+Z2eQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
