apiVersion: v1
kind: Secret
metadata:
  name: librenms-poller-secret
  namespace: librenms
type: Opaque
stringData:
  DB_HOST: "mariadb.librenms.svc.cluster.local"
  DB_NAME: "librenms"
  DB_USER: "librenms"
  DB_PASSWORD: "Pa$$w0rd"
  REDIS_HOST: "redis.librenms.svc.cluster.local"
  REDIS_PORT: "6379"
  APP_KEY: "base64:o/jMPPzPQbvMMRS6LIsdwQAcf6yuREhHik9tRkvTYvU="
