apiVersion: v1
kind: Secret
metadata:
    name: librenms-secret
    namespace: librenms
type: Opaque
stringData:
    db-username: ENC[AES256_GCM,data:ucxKEljNl/Y=,iv:jrnwgtRZtQ1oicDiUwIwGbwfTY1zFmXHRY4YbPEhS6g=,tag:WClasmHMqMbbsVkLx9gEow==,type:str]
    db-password: ENC[AES256_GCM,data:1KbEV5fPCaY=,iv:uAYjFMzjioWnT2uTP8v4Q2su7yRrU4VrGh1n3MiKxbs=,tag:T42siqVj74guvzKSsA/uMw==,type:str]
sops:
    age:
        - recipient: age10953cacvc7svzqscc3rrpxsv7smmkhxj9w3yhcj47dy3a4hgna5shwa46c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRRUg5cjV0eDgwTEdFcHlI
            V21qd2Y4UlVpUTRqMG0wNytONlUxUDkyMUZjCm9vT1lVV1krTWlOMFUrc0JSNStD
            dHNPaTBzY0VKM25lWjBlY3lMTVJjRFEKLS0tIDFOakZLK0ZnTm9mRVZNSVVXMkhX
            T2NCZkZ3SXNRWmEvU1NDRXkzSUY5VGsKyG2YBkjScfXmvZNwbXywoNAHrxrVVoS0
            1wNdSgNymCLTJiL7NyfLNMD65CF8DhivfoLr/wKTQWAUcCUESe+sdA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-14T13:23:14Z"
    mac: ENC[AES256_GCM,data:yvo/PINKI7nyUOacpCDavhIxXElswm+IB6pN75uuCuEhuRZg3+ytkmuadx2fPoJqiIzsgUlgrNiECuef8YAGcftwThp5bOFj+H17NRuIM1zYKYFd8KxU6hQjbsR/k9lPhxog0QnTIlZ1SgvDmOmEeN0sYAZiQ+BO6jT8ZwkASNk=,iv:KftFMNa+RB/LutNzZeriRE+XMt93AxwuhIEiSVyGB5Y=,tag:gOlOqrKRHOFptWm5JM3TTA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
